field.formatter.settings.menu_link:
  type: mapping
  label: 'Menu link formatter settings'
  mapping:
    link_to_target:
      type: boolean
      label: 'Enable link'

field.formatter.settings.menu_link_breadcrumb:
  type: mapping
  label: 'Menu link breadcrumb formatter settings'
  mapping:
    link_to_target:
      type: boolean
      label: 'Enable links'
    parents_only:
      type: boolean
      label: 'Only show the parents of the menu link'

field.storage_settings.menu_link:
  type: mapping
  label: 'Menu link settings'
  mapping:
    menu_link_per_translation:
      type: boolean
      label: Expose a menu link per translation
      
field.field_settings.menu_link:
  type: mapping
  label: 'Menu link settings'
  mapping:
    available_menus:
      type: sequence
      label: 'Available menus'
      sequence:
        - type: string
    default_menu_parent:
      type: string
      label: 'Default menu parent'

field.value.menu_link:
  type: mapping
  label: 'Default value'
  mapping:
    menu_name:
      type: string
      label: 'Value'
    parent:
      type: string
      label: 'Text format'
    weight:
      type: integer
      label: 'Weight'
