<?php

/**
 * @file
 * Hooks implementations.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function geocoder_autocomplete_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.geocoder_autocomplete':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Geographic reference autocomplete') . '</p>';
      $output .= '<p>' . t('Data comes from Google services') . '</p>';
      return $output;

    default:
  }
}
