menu_link_weight.settings:
  type: config_object
  label: 'Menu Link Weight settings'
  mapping:
    menu_parent_form_selector:
      type: string
      label: 'Configure the parent menu link selector widget'
