<?php

/**
 * @file
 * Contains ict_busroutes.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ict_busroutes_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ict_busroutes':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('ICT Bus Routes provides a React-based interface for viewing bus route information.') . '</p>';
      return $output;

    default:
  }
}
