<?php

/**
 * @file
 * Install, update and uninstall functions for the Intercity Transit - Route and Trip Planner Tools module.
 */

/**
 * Implements hook_update_N().
 */
function it_route_trip_tools_update_8001(&$sandbox) {
  $term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->create([
    'name' => 'CALENDAR_PLACEHOLDER',
    'uuid' => '10c284fb-434e-4379-bd72-3448652c0813',
    'vid' => 'calendar_event_type',
  ])->save();
}