field.widget.settings.geocoder_autocomplete:
  type: mapping
  mapping:
    size:
      type: integer
    placeholder:
      type: string
    autocomplete_route_name:
      type: string

geocoder_autocomplete.settings:
  type: config_object
  label: 'Geocoder Autocomplete settings'
  mapping:
    region_code_bias:
      type: string
      label: 'Region code bias'
    api_key:
      type: string
      label: 'Google API key'
