features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://logo_0.jpg'
favicon:
  use_default: 0
  path: 'public://Bus-favicon.png'
  mimetype: image/png
custom_css: 0
disable_google_fonts: 0
