_core:
  default_config_hash: qSffC70ODbv0BehNMS_7K1sO34OogvBsnphKkBeV5W8
admin_css: true
one_pixel: true
blazy:
  loadInvisible: false
  offset: 100
  saveViewportOffsetDelay: 50
max_region_count: 0
