maxlength_block_class_field: 255
field_type: multiple_textfields
default_case: standard
allow_only_letters_and_numbers: false
block_classes_stored:
  - ''
  - col-xs-12
  - col-sm-12
  - col-md-6
  - col-lg-8
  - col-xl-8
  - col-lg-4
  - col-md-4
  - col-sm-5
  - col-xs-5
  - break-lg-control
  - pull-left
  - col-md-8
  - col-lg-12
  - col-xl-12
  - col-md-12
  - col-xl-4
  - it-well-blue
  - break-md-control
  - container
  - col-sm-6
  - clearfix
  - col-xl-3
  - col-lg-3
  - col-md-3
  - walk-n-roll-calendar
  - row
enable_attributes: true
enable_auto_complete: true
qty_classes_per_block: 10
items_per_page: 50
enable_special_chars: true
qty_attributes_per_block: 10
enable_id_replacement: true
weight_attributes: null
weight_class: null
weight_id: null
maxlength_attributes: 255
attribute_keys_stored: '[]'
attribute_value_stored: '[]'
attributes_inline: '[]'
