_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: current
defaults:
  sender: SMTPMailSystem
  formatter: SMTPMailSystem
modules:
  smtp: {  }
  webform:
    none:
      sender: SMTPMailSystem
      formatter: SMTPMailSystem
