_core:
  default_config_hash: eKR4FfUD7Cp3bXamsCz6GAxh0PCLIZNMa65y2kChIh0
site_key: 6LebYholAAAAAOG5Tq1ZJdGi6XJSFzC3eOnxoEQp
secret_key: 6LebYholAAAAAEmDygV8AvZRpHuFf1LCIl485i_o
verify_hostname: false
use_globally: false
widget:
  theme: light
  type: image
  size: ''
  noscript: false
  tabindex: 0
