idp:
  portal_intercitytransit_com: portal_intercitytransit_com
logout: false
logged_in_redirect: '<front>'
update_email: false
update_language: false
no_account_authenticated_user_role: false
no_account_authenticated_user_account: null
force_authentication: false
force_saml_only: true
account_request_request_account: false
