_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 55701b07-b8c9-4fd1-9f96-0fd8d24262ea
name: 'Intercity Transit'
mail: noreply@intercitytransit.com
slogan: ''
page:
  403: ''
  404: /node/217
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: rrinehart@intercitytransit.com
