cacheexclude.settings:
  type: config_object
  label: 'Cache exclude settings'
  mapping:
    cacheexclude_list:
      type: string
      label: 'Pages to exclude from caching'
    cacheexclude_node_types:
      type: sequence
      label: 'Content types to exclude from caching'
      sequence:
        type: string
        label: 'Node types'
